### ISSUE TITLE
baseline_model

### ISSUE THREAD

**Issue by benz871** [obryanlouis/qa#11]
What can be the baseline model for the squad assuming that you get the hidden states of the context and question using a bidirectional GRU separately over context and questions? 
Also did you one-hot encode the answer start or end? If we don't one hot encode and send them directly what could be the side effects of that?

**Comment by obryanlouis** [comment]
The model you suggest in the first question seems similar to FastQa to me. https://arxiv.org/pdf/1703.04816.pdf. The answer starts/ends aren't one-hot encoded in the data. There is a function in tensorflow that will do it, if you need that. I'm not sure what you mean in the last question.
