### ISSUE TITLE
Squad training sample missing

### ISSUE THREAD

**Issue by robbine** [obryanlouis/qa#6]
I read the squad dateset papaer https://arxiv.org/pdf/1606.05250.pdf and found that there are more than 100000 qa pairs. But I run np.load('data/dev/question_ids.0.npy').shape , and there are only 10570 samples remaining. I check the code and find this comment and not sure if it's the reason
''' 
                # Sometimes, the given answer isn't actually in the context.
                # If so, find the smallest surrounding text instead.
'''

**Comment by theSage21** [comment]
That number looks like the Dev set. Training has around 80k and Dev has
about 10k.

The comment may arise since most of these systems enforce a hard limit for
training and sometimes the answer gets cut off.

**Comment by obryanlouis** [comment]
theSage21 is right. IIRC, the code doesn't actually end up throwing any examples out. Although it does truncate the length of passages based on the program flags (I'm not sure if that is the best way to do it).

The comment is actually about a few examples in the dataset where the span actually isn't in the passage. It seems like bad data, but the code tries to correct it with the best guess. It is very few examples.
