### ISSUE TITLE
Piping questions in the model

### ISSUE THREAD

**Issue by benz871** [obryanlouis/qa#9]
Each context has multiple questions attached to it. So how does the model know which question belongs to which context in the given batch or you are just replicating each context for each question that is present to that context.Also how do you generate batches for training and what do you do with the embeddings of those tokens that are not in Glove vocabulary. This issue is bugging for me a long time can you help me with it.also I am new to Tensorflow?

**Comment by obryanlouis** [comment]
Hi Benz871,

1) Yes, it replicates the context for all the questions to make separate training samples. Maybe it's not the most efficient way to do it, but it works.

2) Tokens that aren't in the Glove vocabulary are mapped to the "unk" symbol; they are populated here:
https://github.com/obryanlouis/qa/blob/master/preprocessing/create_train_data.py#L79
and in the "vocab" object any id that isn't found is just mapped to the unk id:
https://github.com/obryanlouis/qa/blob/master/preprocessing/vocab.py#L24
Batches are generated for training starting out in the "preprocessing" folder - you can check this code:
https://github.com/obryanlouis/qa/blob/master/preprocessing/create_train_data.py#L336

You may be wondering what vector is used for unk - this implementation just uses a zero vector. I think you can also try making that a parameter that the model learns (I don't know if it helps much though).
https://github.com/obryanlouis/qa/blob/master/preprocessing/embedding_util.py#L13

I hope that helps

**Comment by benz871** [comment]
Thanks for the help. I just wanted to know what is the use of masking in the inputs?

**Comment by obryanlouis** [comment]
I'm not sure what you mean by masking - do you mean the use of a zero vector? If so, then that is just done to have something for the model to use for unk because there isn't a vector in the embedding for it. I think it is at least somewhat typical.

**Comment by benz871** [comment]
I was browsing through various models for the same task. In addition to a context vector many of them had a additional placeholder which had true or ones upto the length of the context and false or zeroes after the length of context upto maxlength. I was not able to figure out the use for it. It was called the masking placeholder.

**Comment by obryanlouis** [comment]
Ah - was it for padding? Sometimes the context is shorter than the max allowed length. If you do keep track of the length then you can reduce some computation, e.g. in computing LSTM outputs (sequence_length in https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn)

**Comment by benz871** [comment]
Thanks for the help.

**Comment by obryanlouis** [comment]
g/luck
